# Generated by Django 4.2.6 on 2023-11-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report', models.TextField()),
            ],
        ),
    ]
